# zsh main config file

stty -ixon

${PROMPT_SHOW_PARTITION:=false}
${PROMPT_SHOW_TIME:=true}
${PROMPT_SHOW_GIT:=true}

# Source zim
if [[ -s ${ZDOTDIR:-${HOME}}/.zim/init.zsh ]]; then
  source ${ZDOTDIR:-${HOME}}/.zim/init.zsh
fi

unsetopt autocd
unsetopt extendedglob
# allow to trunk file with >
setopt clobber

# The following lines were added by compinstall
zstyle :compinstall filename '/home/mat/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

eval "$(fasd --init zsh-hook zsh-wcomp zsh-wcomp-install zsh-ccomp-install zsh-wcomp-install)"

local mydir=${0:a:h}
source ${mydir}/aliases.sh
source ${mydir}/keybindings.sh
source ${mydir}/prompt_zsh.sh
source ${mydir}/copy_system_clip.zsh

# virtualenv wrapper
# export WORKON_HOME=$HOME/.virtualenvs
# export PROJECT_HOME=$HOME/Devel
# source /usr/bin/virtualenvwrapper.sh
