
stty -ixon

# Source zim
if [[ -s ${ZDOTDIR:-${HOME}}/.zim/init.zsh ]]; then
  source ${ZDOTDIR:-${HOME}}/.zim/init.zsh
fi

unsetopt autocd
unsetopt extendedglob
# allow to trunk file with >
setopt clobber

# The following lines were added by compinstall
zstyle :compinstall filename '/home/mat/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

eval "$(fasd --init zsh-hook zsh-ccomp zsh-ccomp-install zsh-wcomp zsh-wcomp-install)"

local mydir=${0:a:h}
source ${mydir}/keybindings.sh
source ${mydir}/aliases.sh
source ${mydir}/prompt_zsh.sh
source ${mydir}/copy_system_clip.zsh

eval "$(pipenv --completion)"

# start tmux automatically
if [[ ! $TERM =~ screen ]]; then
  exec tmux
fi
